import { useState } from "react";
import Avatar from "./Avatar";
import Icon from "./Icons";
import { api, formatRelativeDate, getUserId, imageUrl } from "../lib";

export default function PostCard({ post, currentUserId, onDelete, onLike }) {
  const postId = post?._id || post?.id; const author = post?.author || {}; const authorId=getUserId(author); const liked=(post?.likes||[]).some(x=>getUserId(x)===String(currentUserId)||String(x?._id||x?.id||x)===String(currentUserId));
  const [comments,setComments]=useState([]); const [open,setOpen]=useState(false); const [text,setText]=useState(""); const [reply,setReply]=useState(null); const [replyText,setReplyText]=useState(""); const [busy,setBusy]=useState(false);
  const loadComments=async()=>{try{const r=await api(`/comments/${postId}`);setComments(r.data?.comments||[])}catch(e){console.error(e)}};
  const addComment=async(parentComment=null)=>{const value=(parentComment?replyText:text).trim();if(!value)return;setBusy(true);try{await api(`/comments/${postId}`,{method:"POST",body:JSON.stringify({content:value,parentComment})});if(parentComment){setReply(null);setReplyText("")}else setText("");await loadComments();setOpen(true)}finally{setBusy(false)}};
  const remove=async id=>{if(!confirm("Delete this comment?"))return;await api(`/comments/${id}`,{method:"DELETE"});await loadComments()};
  const replies=id=>comments.filter(c=>String(c.parentComment?._id||c.parentComment)===String(id));
  const renderComment=c=><div className="comment-item" key={c._id}><Avatar user={c.author} size="sm"/><div className="comment-body"><div className="comment-bubble"><strong>{c.author?.name||"User"}</strong><span>@{c.author?.username||"user"}</span><p>{c.content}</p></div><div className="comment-actions"><button onClick={()=>{setReply(c._id);setReplyText("")}}>Reply</button>{getUserId(c.author)===String(currentUserId)&&<button onClick={()=>remove(c._id)} className="danger-text">Delete</button>}</div>{reply===c._id&&<div className="reply-input"><input value={replyText} onChange={e=>setReplyText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addComment(c._id)} placeholder={`Reply to ${c.author?.name||"user"}`}/><button onClick={()=>addComment(c._id)} disabled={busy}>↗</button></div>}{replies(c._id).map(r=><div className="reply-row" key={r._id}><Avatar user={r.author} size="xs"/><div><strong>{r.author?.name||"User"}</strong><p>{r.content}</p></div></div>)}</div></div>;
  return <article className="post-card panel"><div className="post-head"><button className="author-link" onClick={()=>{if(authorId)location.href=`/profile/${authorId}`}}><Avatar user={author} size="md"/><span><strong>{author?.name||"Unknown User"}</strong><small>@{author?.username||"user"} · {formatRelativeDate(post?.createdAt)}</small></span></button>{authorId===String(currentUserId)&&<button className="icon-btn subtle" title="Delete story" onClick={()=>onDelete(postId)}><Icon name="more"/></button>}</div>{post?.content&&<p className="post-content">{post.content}</p>}{(post?.image||post?.imageUrl)&&<img className="post-image" src={imageUrl(post.image||post.imageUrl)} alt="Story"/>}<div className="post-stats"><span>{post?.likes?.length||0} likes</span><span>{comments.length} comments</span></div><div className="post-actions"><button className={liked?"liked":""} onClick={()=>onLike(postId,liked)}><Icon name="heart"/> {liked?"Liked":"Like"}</button><button onClick={()=>{setOpen(!open);if(!open)void loadComments()}}><Icon name="comment"/> Comment</button><button onClick={()=>navigator.clipboard?.writeText(window.location.href)}><Icon name="share"/> Share</button></div>{open&&<div className="comments-panel"><div className="comment-compose"><Avatar user={JSON.parse(localStorage.getItem("storySphereUser")||"null")} size="sm"/><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addComment()} placeholder="Add a thoughtful comment…"/><button onClick={()=>addComment()} disabled={busy||!text.trim()}>↗</button></div>{comments.filter(c=>!c.parentComment).length?comments.filter(c=>!c.parentComment).map(renderComment):<div className="empty-small">No comments yet. Start the conversation.</div>}</div>}</article>;
}
