import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Layout from "../components/Layout";
import Avatar from "../components/Avatar";
import Icon from "../components/Icons";
import { api, getCurrentUser } from "../lib";

export default function CreatePost(){const navigate=useNavigate();const user=getCurrentUser();const [content,setContent]=useState("");const [image,setImage]=useState(null);const [preview,setPreview]=useState("");const [visibility,setVisibility]=useState("public");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 const pick=e=>{const f=e.target.files?.[0];if(!f)return;setImage(f);setPreview(URL.createObjectURL(f))};
 const submit=async e=>{e.preventDefault();if(!content.trim()&&!image){setError("Add some words or a photo to publish your story.");return}setLoading(true);setError("");try{const fd=new FormData();fd.append("content",content);fd.append("visibility",visibility);if(image)fd.append("image",image);await api("/posts",{method:"POST",body:fd});navigate("/posts")}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <Layout title="Create story" subtitle="Put something good into the sphere"><div className="create-page"><div className="create-intro"><span className="eyebrow">CREATE</span><h1>Your story, your way.</h1><p>Write a thought, share a moment or drop a photo into the community.</p></div><form className="create-card panel" onSubmit={submit}><div className="create-author"><Avatar user={user} size="md"/><div><strong>{user?.name||"Vikash"}</strong><span>@{user?.username||"storylover"}</span></div><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">🌎 Public</option><option value="private">🔒 Private</option></select></div><textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={5000} placeholder="Tell your story…" autoFocus/><div className="create-toolbar"><label className="upload-btn"><Icon name="image"/><span>{image?"Change photo":"Add photo"}</span><input type="file" accept="image/*" onChange={pick}/></label><span className="char-count">{content.length}/5000</span></div>{preview&&<div className="preview-wrap"><img src={preview} alt="Preview"/><button type="button" onClick={()=>{setImage(null);setPreview("")}}><Icon name="close" size={17}/></button></div>}{error&&<div className="error-banner">{error}</div>}<div className="create-actions"><button type="button" className="ghost-btn" onClick={()=>navigate("/posts")}>Cancel</button><button className="primary-btn" disabled={loading}>{loading?<><span className="mini-spinner"/> Publishing…</>:<>Publish story <Icon name="arrow"/></>}</button></div></form></div></Layout>}
