import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import logo from "../assets/story-sphere-logo.png";
import sphereIcon from "../assets/story-sphere-icon.png";
import Icon from "../components/Icons";
import { API_URL } from "../lib";

export default function Login() {
  const navigate = useNavigate(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const submit = async e => { e.preventDefault(); setError(""); setLoading(true); try { const r=await fetch(`${API_URL}/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})}); const data=await r.json(); if(!r.ok||!data.success) throw new Error(data.message||"Unable to sign in"); localStorage.setItem("storySphereToken",data.data.token); localStorage.setItem("storySphereUser",JSON.stringify(data.data.user)); navigate("/home",{replace:true}); } catch(e){setError(e.message);} finally{setLoading(false);} };
  return <div className="auth-page"><div className="auth-visual"><div className="auth-orb"/><img src={logo} alt="Story Sphere"/><span>Stories. People. Moments. One sphere.</span><div className="auth-pills"><b>✦ Share</b><b>◌ Connect</b><b>♡ Belong</b></div></div><div className="auth-panel"><div className="auth-brand"><img src={sphereIcon} alt=""/><strong>Story<span>Sphere</span></strong></div><div className="auth-copy"><span className="eyebrow">WELCOME BACK</span><h1>Sign in to your sphere.</h1><p>Pick up where your stories and conversations left off.</p></div><form onSubmit={submit} className="auth-form"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required autoComplete="email"/></label><label>Password<div className="password-field"><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)}><Icon name="eye" size={18}/></button></div></label>{error&&<div className="error-banner">{error}</div>}<button className="primary-btn wide" disabled={loading}>{loading?<><span className="mini-spinner"/> Signing in…</>:<>Sign in <Icon name="arrow"/></>}</button></form><div className="auth-divider"><span>New to Story Sphere?</span></div><Link className="secondary-btn wide" to="/register">Create an account <Icon name="plus" size={18}/></Link><p className="auth-footer">By continuing, you agree to use Story Sphere respectfully and safely.</p></div></div>;
}
