import { useEffect, useMemo, useRef, useState } from "react";
import sphereIcon from "../assets/story-sphere-icon.png";
import { useNavigate, useSearchParams } from "react-router-dom";
import Layout from "../components/Layout";
import Avatar from "../components/Avatar";
import Icon from "../components/Icons";
import Loader from "../components/Loader";
import { API_URL, api, formatTime, getCurrentUser, getUserId } from "../lib";

export default function Messages(){
 const navigate=useNavigate(); const [params]=useSearchParams(); const me=getCurrentUser(); const myId=String(getUserId(me)); const [users,setUsers]=useState([]); const [selectedId,setSelectedId]=useState(params.get("user")||""); const [messages,setMessages]=useState([]); const [text,setText]=useState(""); const [loading,setLoading]=useState(true); const [chatLoading,setChatLoading]=useState(false); const [query,setQuery]=useState(""); const [connected,setConnected]=useState(false); const endRef=useRef(null); const selected=users.find(u=>String(getUserId(u))===String(selectedId))||null;  const selectedRef=useRef(null);
 useEffect(()=>{selectedRef.current=selected},[selected]);
 useEffect(()=>{api("/users").then(r=>setUsers(r.data?.users||[])).catch(console.error).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!selected)return;api(`/messages/${getUserId(selected)}`).then(r=>setMessages(r.data?.messages||[])).catch(console.error).finally(()=>setChatLoading(false));api(`/messages/${getUserId(selected)}/read`,{method:"PATCH"}).catch(()=>{});},[selected]);
 useEffect(()=>{const token=localStorage.getItem("storySphereToken");if(!token)return;const controller=new AbortController();let buffer="";fetch(`${API_URL}/messages/stream`,{headers:{Authorization:`Bearer ${token}`,Accept:"text/event-stream"},signal:controller.signal}).then(async res=>{if(!res.ok||!res.body)throw new Error("stream unavailable");setConnected(true);const reader=res.body.getReader();const decoder=new TextDecoder();while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split("\n\n");buffer=blocks.pop()||"";for(const block of blocks){const dataLine=block.split("\n").find(x=>x.startsWith("data:"));const eventLine=block.split("\n").find(x=>x.startsWith("event:"));if(!dataLine||eventLine?.includes("ready"))continue;try{const payload=JSON.parse(dataLine.slice(5).trim());const m=payload.message;const active=selectedRef.current;if(!m||!active)continue;const sender=String(getUserId(m.sender));const receiver=String(getUserId(m.receiver));const other=String(getUserId(active));if((sender===myId&&receiver===other)||(sender===other&&receiver===myId))setMessages(prev=>prev.some(x=>String(x._id)===String(m._id))?prev:[...prev,m]);}catch(error){console.error(error)}}}}).catch(()=>setConnected(false));return()=>controller.abort()},[myId]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 const filtered=useMemo(()=>users.filter(u=>`${u.name} ${u.username}`.toLowerCase().includes(query.toLowerCase())),[users,query]);
 const send=async()=>{if(!text.trim()||!selected)return;const content=text.trim();setText("");try{const r=await api("/messages",{method:"POST",body:JSON.stringify({receiverId:getUserId(selected),content})});const m=r.data?.message;if(m)setMessages(prev=>prev.some(x=>String(x._id)===String(m._id))?prev:[...prev,m]);}catch(e){setText(content);alert(e.message)}};
 const key=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};
 return <Layout title="Messages" subtitle={connected?"Live connection active":"Connecting to live chat…"}><div className={`messages-page ${selected?"mobile-chat-open":""}`}>
  <section className="conversation-list"><div className="messages-heading"><h1>Messages</h1><p><span className="online-dot"/> {connected?"Real-time messaging is on":"Connecting…"}</p></div><input className="message-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people…"/><div className="conversation-scroll">{loading?<Loader label="Loading people…"/>:filtered.map(u=><button className={`conversation-item ${selected&&getUserId(selected)===getUserId(u)?"active":""}`} key={getUserId(u)} onClick={()=>setSelectedId(getUserId(u))}><Avatar user={u} size="md"/><span><strong>{u.name}</strong><small>@{u.username}</small></span><Icon name="arrow" size={16}/></button>)}</div></section>
  <section className="chat-panel">{!selected?<div className="chat-empty"><div><img src={sphereIcon} alt=""/><h2>Your conversations live here.</h2><p>Select a person and start a real-time conversation.</p></div></div>:<><div className="chat-head"><div className="chat-user"><Avatar user={selected} size="sm"/><span><strong>{selected.name}</strong><small><span className="online-dot"/> Live chat</small></span></div><button className="ghost-btn" onClick={()=>navigate(`/profile/${getUserId(selected)}`)}>View profile</button></div>{chatLoading?<Loader full label="Loading conversation…"/>:<><div className="chat-messages">{messages.length===0?<div className="empty-small">No messages yet. Say hello 👋</div>:messages.map(m=>{const mine=String(getUserId(m.sender))===myId;return <div key={m._id} className={`message-bubble-row ${mine?"mine":""}`}><div className="message-bubble">{m.content&&<div>{m.content}</div>}<time>{formatTime(m.createdAt)}</time></div></div>})}<div ref={endRef}/></div><div className="chat-input"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={key} placeholder="Write a message…" rows={1}/><button onClick={send} disabled={!text.trim()} title="Send"><Icon name="share" size={19}/></button></div></>}</>}</section>
 </div></Layout>
}
