import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import Layout from "../components/Layout";
import Avatar from "../components/Avatar";
import Icon from "../components/Icons";
import Loader from "../components/Loader";
import { api, formatRelativeDate, getUserId } from "../lib";
export default function Notifications(){const navigate=useNavigate();const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const load=async()=>{try{const r=await api("/notifications");setItems(r.data?.notifications||[])}catch(e){console.error(e)}finally{setLoading(false)}};// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{void load()},[]);const read=async n=>{if(!n.isRead){await api(`/notifications/${n._id}/read`,{method:"PATCH"});setItems(x=>x.map(i=>i._id===n._id?{...i,isRead:true}:i))}};const all=async()=>{await api("/notifications/read-all",{method:"PATCH"});setItems(x=>x.map(i=>({...i,isRead:true})))};return <Layout title="Alerts" subtitle="Stay close to what is happening"><div className="notifications-page"><div className="section-heading"><div><span className="eyebrow">ACTIVITY</span><h1 style={{margin:"7px 0 0",fontSize:32}}>Your notifications</h1><p>Likes, follows, comments and messages in one place.</p></div><button className="ghost-btn" onClick={all}><Icon name="check"/> Mark all read</button></div>{loading?<Loader full/>:items.length===0?<div className="empty-state panel"><span>♡</span><h2>You're all caught up</h2><p>New activity will appear here.</p></div>:<div className="user-results">{items.map(n=><button key={n._id} className={`panel notification-card ${n.isRead?"":"unread"}`} onClick={()=>{read(n);if(n.sender)navigate(`/profile/${getUserId(n.sender)}`)}}><Avatar user={n.sender} size="sm"/><span><strong>{n.text||`${n.type} activity`}</strong><small>{formatRelativeDate(n.createdAt)}</small></span>{!n.isRead&&<span className="online-dot"/>}<Icon name="arrow" size={16}/></button>)}</div>}</div></Layout>}
