import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Layout from "../components/Layout";
import Avatar from "../components/Avatar";
import Icon from "../components/Icons";
import Loader from "../components/Loader";
import { api, getCurrentUser, getUserId, imageUrl } from "../lib";

export default function Profile(){const {userId}=useParams();const navigate=useNavigate();const me=getCurrentUser();const [user,setUser]=useState(null);const [posts,setPosts]=useState([]);const [tab,setTab]=useState("about");const [loading,setLoading]=useState(true);const [following,setFollowing]=useState(false);const [busy,setBusy]=useState(false);const isOwn=String(getUserId(me))===String(userId);
 const load=async()=>{try{const [u,p]=await Promise.all([api(`/users/${userId}`),api("/posts")]);const profile=u.data?.user;setUser(profile);setPosts((p.data?.posts||[]).filter(x=>String(getUserId(x.author))===String(userId)));setFollowing((profile?.followers||[]).some(x=>String(getUserId(x))===String(getUserId(me))))}catch(e){console.error(e)}finally{setLoading(false)}};
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[userId]);
 const follow=async()=>{setBusy(true);try{await api(`/users/${userId}/follow`,{method:following?"DELETE":"POST"});setFollowing(!following);setUser({...user,followers:following?(user.followers||[]).filter(x=>String(getUserId(x))!==String(getUserId(me))):[...(user.followers||[]),me]})}catch(e){alert(e.message)}finally{setBusy(false)}};
 if(loading)return <Layout title="Profile"><Loader full label="Loading profile…"/></Layout>; if(!user)return <Layout title="Profile"><div className="empty-state panel"><span>◌</span><h2>Profile unavailable</h2><button className="primary-btn" onClick={()=>navigate("/search")}>Discover people</button></div></Layout>;
 return <Layout title="Profile" subtitle={`@${user.username}`}><div className="profile-page"><section className="panel" style={{overflow:"hidden"}}><div className="profile-cover"/><div className="profile-body"><div className="profile-top"><div className="profile-avatar-ring"><Avatar user={user} size="xl"/></div><div className="profile-actions">{!isOwn&&<><button className={following?"ghost-btn":"primary-btn"} onClick={follow} disabled={busy}>{following?"Following":"Follow"}</button><button className="ghost-btn" onClick={()=>navigate(`/messages?user=${userId}`)}><Icon name="message"/> Message</button></>}{isOwn&&<button className="ghost-btn" onClick={()=>navigate("/settings")}><Icon name="settings"/> Settings</button>}</div></div><div className="profile-info"><h1>{user.name}</h1><p>@{user.username}</p><div className="profile-stats"><div className="profile-stat"><strong>{posts.length}</strong><span>Stories</span></div><button className="profile-stat" onClick={()=>setTab("followers")}><strong>{user.followers?.length||0}</strong><span>Followers</span></button><button className="profile-stat" onClick={()=>setTab("following")}><strong>{user.following?.length||0}</strong><span>Following</span></button></div><p className="profile-bio">{user.bio||"No bio yet. This space is waiting for a story."}</p></div><div className="profile-tabs"><button className={tab==="about"?"active":""} onClick={()=>setTab("about")}>About</button><button className={tab==="followers"?"active":""} onClick={()=>setTab("followers")}>Followers</button><button className={tab==="following"?"active":""} onClick={()=>setTab("following")}>Following</button><button className={tab==="stories"?"active":""} onClick={()=>setTab("stories")}>Stories</button></div></div></section>
 {tab==="stories"?<div className="profile-stories">{posts.length?posts.map(p=><div className="panel story-mini" key={p._id}><p>{p.content||"Photo story"}</p>{p.image&&<img src={imageUrl(p.image)} alt=""/>}</div>):<div className="empty-state panel"><span>✦</span><h2>No stories yet</h2></div>}</div>:<div className="follow-lists"><section className="panel follow-card"><h3>Followers <small>({user.followers?.length||0})</small></h3>{(user.followers||[]).length?user.followers.slice(0,8).map(x=><button className="follow-user" key={getUserId(x)} onClick={()=>navigate(`/profile/${getUserId(x)}`)}><Avatar user={x} size="sm"/><span><strong>{x.name}</strong><small>@{x.username}</small></span><Icon name="arrow" size={15}/></button>):<div className="empty-small">No followers to show yet.</div>}</section><section className="panel follow-card"><h3>Following <small>({user.following?.length||0})</small></h3>{(user.following||[]).length?user.following.slice(0,8).map(x=><button className="follow-user" key={getUserId(x)} onClick={()=>navigate(`/profile/${getUserId(x)}`)}><Avatar user={x} size="sm"/><span><strong>{x.name}</strong><small>@{x.username}</small></span><Icon name="arrow" size={15}/></button>):<div className="empty-small">Not following anyone yet.</div>}</section></div>}
 </div></Layout>}
