import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import logo from "../assets/story-sphere-logo.png";
import sphereIcon from "../assets/story-sphere-icon.png";
import Icon from "../components/Icons";
import { API_URL } from "../lib";

export default function Register(){
 const navigate=useNavigate(); const [form,setForm]=useState({name:"",username:"",email:"",password:""}); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const update=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();setError("");setLoading(true);try{const r=await fetch(`${API_URL}/auth/register`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Unable to create account");localStorage.setItem("storySphereToken",d.data.token);localStorage.setItem("storySphereUser",JSON.stringify(d.data.user));navigate("/home",{replace:true});}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <div className="auth-page register-page"><div className="auth-visual"><div className="auth-orb"/><img src={logo} alt="Story Sphere"/><span>Your next chapter starts here.</span><div className="register-quote"><strong>“Every voice deserves a place in the sphere.”</strong><small>Build your circle. Tell your story.</small></div></div><div className="auth-panel"><div className="auth-brand"><img src={sphereIcon} alt=""/><strong>Story<span>Sphere</span></strong></div><div className="auth-copy"><span className="eyebrow">JOIN THE SPHERE</span><h1>Create your account.</h1><p>Make a profile, meet people and share the moments that matter.</p></div><form onSubmit={submit} className="auth-form"><div className="form-two"><label>Full name<input name="name" value={form.name} onChange={update} placeholder="Your name" required/></label><label>Username<input name="username" value={form.username} onChange={update} placeholder="yourhandle" required minLength={3}/></label></div><label>Email<input type="email" name="email" value={form.email} onChange={update} placeholder="you@example.com" required/></label><label>Password<div className="password-field"><input type={show?"text":"password"} name="password" value={form.password} onChange={update} placeholder="At least 6 characters" required minLength={6}/><button type="button" onClick={()=>setShow(!show)}><Icon name="eye" size={18}/></button></div></label>{error&&<div className="error-banner">{error}</div>}<button className="primary-btn wide" disabled={loading}>{loading?<><span className="mini-spinner"/> Creating…</>:<>Create account <Icon name="arrow"/></>}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p><p className="auth-footer">Use a unique username and a strong password to keep your account secure.</p></div></div>;
}
